name: Build macOS

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Git reference (branch/tag) to build
        default: 'main'
      bazelBuildArgs:
        type: string
        description: Bazel build options
        default: '--experimental_scale_timeouts=10.0 --http_timeout_scaling=10.0'
      macosBuildArgs:
        type: string
        required: false
        default: '--desktop cpu --opencv cmake --macos_universal'
        description: Build options for macOS Build (skip if empty)

jobs:
  macos-build:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install NuGet
        run: brew install nuget

      # Setup Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install NumPy
        run: pip install --no-cache-dir --user numpy

      - name: Build libmediapipe_c.dylib
        if: ${{ inputs.macosBuildArgs != '' }}
        run: |
          unset ANDROID_NDK_HOME
          python build.py build --bazel_build_opts="${{ inputs.bazelBuildArgs }}" ${{ inputs.macosBuildArgs }} -vv

      - name: Upload libmediapipe_c.dylib
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: Packages/com.github.homuler.mediapipe/Runtime/Plugins/libmediapipe_c.dylib*
